on:
  workflow_call:
    inputs:
      src:
        required: true
        type: string
        default: 'deploy'
      aws-role-to-assume:
        required: true
        type: string
        default: 'arn:aws:iam::258900779417:role/github-deployer'
      aws-region:
        required: true
        type: string
        default: 'eu-west-2'
      aws-role-session-name:
        required: true
        type: string
      deploy-stack-name:
        required: true
        type: string
      deploy-require-approval-for-iam-changes:
        required: true
        type: string
        default: 'never'
      deployment-id:
        required: false
        type: string
      deployment-env:
        required: true
        type: string
        default: 'dev'
    secrets:
      registry-token:
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.src }}

      - name: Deployment pending
        if: ${{ inputs.deployment-id != ''}}
        uses: 'maxkomarychev/oction-create-deployment-status@v0.7.1'
        with:
          token: ${{ github.token }}
          deployment_id: ${{ inputs.deployment-id }}
          state: 'pending'
          description: ${{ inputs.deploy-stack-name }}

      - name: 'Deploying to ${{ inputs.deployment-env }}'
        run: |
          echo "stack - ${{ inputs.deploy-stack-name }}"
          echo "environment - ${{ inputs.deployment-env }}"
          echo "cdk approval required - ${{ inputs.deploy-require-approval-for-iam-changes }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-session-name: ${{ inputs.aws-role-session-name }}
          aws-region: ${{ inputs.aws-region }}

      - name: Fetch Dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.registry-token }}
        working-directory: ${{ inputs.src }}
        shell: bash
        run: |
          npm ci --ignore-scripts
          export NODE_AUTH_TOKEN="BOGUS"
          npm rebuild
          npm run prepare --if-present

      - name: Deploy
        working-directory: deploy
        shell: bash
        run: |
          ./node_modules/.bin/cdk --app "npm run-script deploy" deploy ${{ inputs.deploy-stack-name }} --require-approval ${{ inputs.deploy-require-approval-for-iam-changes }} --ci

      - name: Deployment successful
        if: ${{ inputs.deployment-id != '' && success()}}
        uses: 'maxkomarychev/oction-create-deployment-status@v0.7.1'
        with:
          token: ${{ github.token }}
          deployment_id: ${{ inputs.deployment-id }}
          state: 'success'
          description: ${{ inputs.deploy-stack-name }}

      - name: Deployment failed
        if: ${{ inputs.deployment-id != '' && failure()}}
        uses: 'maxkomarychev/oction-create-deployment-status@v0.7.1'
        with:
          token: ${{ github.token }}
          deployment_id: ${{ inputs.deployment-id }}
          state: 'failure'
          description: ${{ inputs.deploy-stack-name }}