on:
  workflow_call:
    inputs:
      src:
        required: true
        type: string
        default: 'deploy'
    secrets:
      registry-token:
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.src }}

      - name: Fetch Dependencies
        env:
          NODE_AUTH_TOKEN: ${{ inputs.registry-token }}
        working-directory: ${{ inputs.src }}
        shell: bash
        run: |
          npm ci --ignore-scripts
          export NODE_AUTH_TOKEN="BOGUS"
          npm rebuild
          npm run prepare --if-present

      - name: Build
        working-directory: ${{ inputs.src }}
        shell: bash
        run: |
          npm run-script build

      - name: Lint
        working-directory: ${{ inputs.src }}
        shell: bash
        run: |
          npm run-script lint
