on:
  workflow_call:
    inputs:
      image-artifact-name:
        required: true
        type: string
      image-digest:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-20.04
    name: Publish Docker Image to ECR
    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.image-artifact-name }}
          path: /tmp

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ inputs.image-artifact-name }}.tar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::258900779417:role/github-deployer
          role-session-name: elm-container-push
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.0.2

      - name: Publish Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag ${{ inputs.image-digest }} $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Logout of Amazon ECR
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
